services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deepface
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d deepface",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - experiment-network

networks:
  experiment-network:
    driver: bridge