[project]
name = "2dv50e-bachelor-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepface>=0.0.98",
    "insightface>=0.7.3",
    "onnxruntime>=1.24.4",
    "psycopg[binary]>=3.3.3",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.47",
    "tf-keras>=2.20.1",
]
